parameters:
- name: webAppName
  default: ''
- name: blobContainer
  default: ''
- name: cdnEndpoint
  default: ''
- name: isMain
  default: ''
- name: isProduction
  default: ''

jobs:
- job: AssetPipeline
  displayName: Asset Pipeline

  variables:
  - template: ../vars/global.yaml
  - ${{ if eq(lower(variables.isMain), 'true') }}:
    - template: ../vars/dev.yaml
  - ${{ if eq(lower(variables.isProduction), 'true') }}:
    - template: ../vars/prod.yaml

  steps:
  - template: ../steps/debug.yaml
  - script: |
      echo 'isMain - $(isMain)'
      echo 'isProduction - $(isProduction)'
      echo 'webAppName - $(webAppName)'
      echo 'blobContainer - $(blobContainer)'
      echo 'cdnEndpoint - $(cdnEndpoint)'
    displayName: Debug
  # - script: |
  #     npm ci
  #     npm run compile-sass
  #   displayName: 'Compile Sass to CSS'

  # - task: AzureCLI@2
  #   displayName: Assets - Upload and Purge Cache
  #   inputs:
  #     azureSubscription: $(armConnection)
  #     scriptType: bash
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       az --version
  #       az storage container list --account-name $(storageAccount) -o table
  #       az storage blob upload-batch \
  #         --account-name $(storageAccount) \
  #         --source ./assets \
  #         --destination ${{ parameters.blobContainer }}

# az cdn endpoint purge \
#   --resource-group $(resourceGroup) \
#   --name $(cdnEndpoint) \
#   --profile-name $(cdnProfileName) \
#   --content-paths '/css/*' '/images/*'
