# steps:
# - script: echo "##vso[task.setvariable variable=imageTag]$(npm run --silent my-version)"
#   displayName: Override imageTag with app version
#   condition: ${{ variables.isProduction }}

# # - template: steps/debug.yaml

# - task: AzureWebAppContainer@1
#   displayName: "App Service - deploy container"
#   inputs:
#     appName:  $(webAppName)
#     azureSubscription: $(armConnection)
#     imageName: $(dockerRegistry)/$(imageName):$(imageTag)