steps:
- script: |
    npm ci
    npm run compile-sass
  displayName: 'Compile Sass to CSS'

- task: AzureCLI@2
  displayName: Assets - Upload and Purge Cache
  inputs:
    azureSubscription: $(armConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version

      az storage blob upload-batch \
        --account-name $(storageAccount) \
        --source ./assets \
        --destination $(blobContainer)

      az cdn endpoint purge \
        --resource-group $(resourceGroup) \
        --name $(cdnEndpoint) \
        --profile-name $(cdnProfileName) \
        --content-paths '/css/*' '/images/*'
