name: $(BuildID)

trigger:
- production

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: vars/global.yaml

stages:
- stage: Deployment

  # need stage scope to process values 🤨
  variables:
  - ${{ if eq(variables.isMain, 'True') }}:
    - template: vars/dev.yaml
  - ${{ if eq(variables.isProduction, 'True') }}:
    - template: vars/prod.yaml

  jobs:
  - template: jobs/app-service.yaml
  - template: jobs/asset-pipeline.yaml
