name: $(BuildID)

trigger:
  batch: true
  branches:
    include:
    - fix/*
    - feat/*
    - main
  tags:
    include:
    - v*
  paths:
    exclude:
    - README.md

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    always: true
    branches:
      include:
      - main

variables:
- template: vars/global.yaml

stages:

# Tests
# -----
- stage: TestStage
  displayName: Tests (Node.js)
  condition: eq(variables.isTag, 'False')
  jobs:
  - template: jobs/tests.yaml

# Build
# -----
- stage: DockerStage
  displayName: Build (Docker)
  condition: or(eq(variables.isTag,'True'), and(succeeded(), eq(variables.deployMain,'True')))
  variables:
  - ${{ if eq(variables.isMain, 'True') }}:
    - template: vars/dev.yaml
  - ${{ if eq(variables.isProduction, 'True') }}:
    - template: vars/prod.yaml
  jobs:
  - template: jobs/docker.yaml

  # Deploy
  # ------
- stage: DeployStage
  displayName: Deploy (App Service)
  condition: and(succeeded(), eq(variables.deployMain,'True'))
  variables:
  - ${{ if eq(variables.isMain, 'True') }}:
    - template: vars/dev.yaml
  - ${{ if eq(variables.isProduction, 'True') }}:
    - template: vars/prod.yaml
  jobs:
  - template: jobs/app-service.yaml
  - template: jobs/asset-pipeline.yaml
