name: $(BuildID)

trigger:
  branches:
    include:
    - fix/*
    - feat/*
    - main
    - refactor/more-ci
  tags:
    include:
    - v*
  paths:
    exclude:
    - README.md

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    always: true
    branches:
      include:
      - main

variables:
- template: vars/global.yaml

stages:

# Tests
# -----
- stage: Tests
  displayName: Tests (Node.js)
  condition: not(variables.isTag)
  jobs:
  - template: jobs/tests.yaml

# Build
# -----
- stage: DockerBuild
  displayName: Build (Docker)
  condition: or(variables.isTag, and(succeeded(), variables.isMain, variables.isTrustedCI))
  variables:
    - group: nodejs-demo-kv
    - ${{ if eq(variables.isMain, 'True') }}:
      - template: vars/dev.yaml
    - ${{ if eq(variables.isProduction, 'True') }}:
      - template: vars/prod.yaml
  jobs:
  - template: jobs/docker.yaml

  # Deploy
  # ------
- stage: Deploy
  displayName: Deploy (App Service)
  condition: and(succeeded(), variables.isTrustedCI, or(variables.isMain, variables.isProduction))
  variables:
  - ${{ if eq(variables.isMain, 'True') }}:
    - template: vars/dev.yaml
  - ${{ if eq(variables.isProduction, 'True') }}:
    - template: vars/prod.yaml
  jobs:
  - template: jobs/app-service.yaml
  # - template: jobs/asset-pipeline.yaml # Re-enable later. CDN purge takes forever.
