name: $(BuildID)

trigger:
  branches:
    include:
    # - fix/*
    # - feat/*
    # - main
    - feat/split-pipeline
  tags:
    include:
    - v*
  paths:
    exclude:
    - README.md

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

# schedules:
#   - cron: "0 12 * * 0"
#     displayName: Weekly Sunday build
#     always: true
#     branches:
#       include:
#       - main

variables:
  isMain:       true # ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  isTag:        ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}
  notFork:      ${{ eq(variables['System.PullRequest.IsFork'], 'False') }}
  notPR:        ${{ ne(variables['Build.Reason'], 'PullRequest') }}
  notSchedule:  ${{ ne(variables['Build.Reason'], 'Schedule') }}
  isTrustedCI:  ${{ and(variables.notFork, variables.notPR, variables.notSchedule) }}

  # Docker@2 Task needes global scope 🙄
  # registryConnection: onazureio-registry-connection

stages:
# - stage: Tests
#   condition: not(${{ variables.isTag }})
#   jobs:
#   - job: Tests
#     steps:
#     - script: |
#         echo 'hello world'
#     - script: npm ci
#       displayName: npm install

#     - script: npm audit --audit-level=moderate
#       displayName: npm audit (dev)
#       continueOnError: true

#     - script: npm audit --production --audit-level=high
#       displayName: npm audit (prod)

#     - script: npm run lint
#       displayName: linter

#     - script: npm run test
#       displayName: tests

- stage: Build
  displayName: Build Docker Image
  condition: or(${{ variables.isTag }}, and(succeeded(), ${{ variables.isMain }}, ${{ variables.isTrustedCI }}))
  variables:
    dockerRegistry: nodejsdemo.azurecr.io
    imageName:      azure-nodejs-demo
    ${{ if eq(variables.isTag, 'False') }}:
      imageTag: dev
    ${{ if eq(variables.isTag, 'True') }}:
      imageTag: ${{ replace(variables['Build.SourceBranch'], 'refs/tags/v', '') }}
  jobs:
  - job: Build
    variables:
    - group: nodejs-demo-kv
    - name: dockerTag
      value: ${{ variables.dockerRegistry }}/${{ variables.imageName }}:${{ variables.imageTag }}
    steps:
    - bash: |
        echo '[default] dockerTag: $(dockerTag)'
        echo '[default] imageTag: $(imageTag)'
        echo '[default] isTag: $(isTag)'
        echo '[default] isMain: $(isMain)'
        echo '[default] isTrustedCI: $(isTrustedCI)'
      displayName: 'Debug: values'

    - bash: docker build -t $(dockerTag) .
      displayName: docker build

    - task: SnykSecurityScan@0
      displayName: Snyk Container Security Scan
      inputs:
        serviceConnectionEndpoint: 'snyk-api-connection'
        testType: 'container'
        dockerImageName: $(dockerTag)
        dockerfilePath: 'Dockerfile'
        monitorOnBuild: true
        failOnIssues: true

    - bash: docker login $(dockerRegistry) --username $ACR_USERNAME --password $ACR_PASSWORD
      displayName: docker login
      env:
        ACR_USERNAME: $(kv-acr-username)
        ACR_PASSWORD: $(kv-acr-password)

    - bash: docker push $(dockerTag)
      displayName: docker push

    - bash: docker logout $(dockerRegistry)
      displayName: docker logout


