variables:

  # ARM
  armConnection:    nodejs-demo-rg-conn
  resourceGroup:    nodejs-demo-rg
  cdnProfileNaame:  demoassetpipeline

  # Pipeline conditions
  isMain:           ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  isTag:            ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}
  notFork:          ${{ eq(variables['System.PullRequest.IsFork'], 'False') }}
  notPR:            ${{ ne(variables['Build.Reason'], 'PullRequest') }}
  notSchedule:      ${{ ne(variables['Build.Reason'], 'Schedule') }}
  isTrustedCI:      ${{ and(variables.notFork, variables.notPR, variables.notSchedule) }}

  # Docker
  dockerRegistry:   nodejsdemo.azurecr.io
  imageName:        azure-nodejs-demo
  ${{ if eq(variables.isTag, 'False') }}:
    imageTag:       dev
  ${{ if eq(variables.isTag, 'True') }}:
    imageTag:       ${{ replace(variables['Build.SourceBranch'], 'refs/tags/v', '') }}
  dockerTag:        ${{ variables.dockerRegistry }}/${{ variables.imageName }}:${{ variables.imageTag }}